week6/away_days/config/routes.rb
Rails.application.routes.draw do
  # get 'static/home'
  #
  # get '/ground', to: 'ground#index'

  root 'static#home'

  resources :grounds do
    resources :topics
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

week6/away_days/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

week6/away_days/app/models/ground.rb
class Ground < ApplicationRecord
end

week6/away_days/app/models/topic.rb
class Topic < ApplicationRecord
end

week6/away_days/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

week6/away_days/app/controllers/grounds_controller.rb
class GroundsController < ApplicationController
  def index
    # display all the grounds on the index page
    @grounds = Ground.all
  end

  def show
    # target an inidividual ground
    @ground = Ground.find params[:id]
  end

  def new
    # create a new instance of the class: "Ground"
    @ground = Ground.new
  end

  def edit
    # target the ground in which we wish to edit
    @ground = Ground.find params[:id]
  end

  def create
    # create a new instance of the class: "Ground" and pass in the values of ground_params to give it information
    @ground = Ground.new ground_params
    # save the newly created ground
    @ground.save
    # re-direct to the newly created ground page
    redirect_to @ground
  end

  def update
    # locate the ground in which we wish to update
    @ground = Ground.find params[:id]
    # update the ground
    @ground.update ground_params
    # re-direct to the ground's updated page
    redirect_to @ground
  end

  def destroy
    # locate the ground in which we wish to delete
    @ground = Ground.find params[:id]
    # delete the ground
    @ground.delete
    # redirect to the root of the grounds
    redirect_to grounds_path
  end

  def ground_params
    # params will access the information sent by the form
    # require(:ground) targets the specific section of the params
    # permit grants write access to the specified attributes 
    ground_params = params.require(:ground).permit(:name, :location, :desc)
  end
end

week6/away_days/app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

week6/away_days/app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_action :set_ground

  def new
    # create a new instance of the "Topic" class
    @topic = Topic.new
  end

  def edit
    # locate the topic in which we wish to edit
    @topic = Topic.find params[:id]
  end

  def create
    # create a new instance of the "Topic" class
    @topic = @subject.topic.create(topic_params)
    # save the newly created topic
    @topic.save
    # redirect to the corresponding subject
    redirect_to @subject
  end

  def update
    # locate the topic in which we wish to update
    @topic = Topic.find params[:id]
    # update the corresponding topic
    @topic.update topic_params
  end

  def destroy
    # target the topic which we wish to delete
    @topic = Topic.find params[:id]
    # delete the corresponding topic
    @topic.delete
    # redirect to the corresponding ground
    redirect_to @ground
  end

  def topic_params
    topic_params = params.require(:topic).permit(:pubs, :travel)
  end

  def set_ground
    # find the ground which the topic corresponds to
    @ground = Ground.find params[:ground_id]
end

week6/away_days/app/helpers/application_helper.rb
module ApplicationHelper
end

week6/away_days/app/helpers/grounds_helper.rb
module GroundsHelper
end

week6/away_days/app/helpers/static_helper.rb
module StaticHelper
end

week6/away_days/app/helpers/topics_helper.rb
module TopicsHelper
end

week6/away_days/app/views/grounds/_form.html.erb
<%= form_for ground do |g| %>
  <div class="field">
    <!-- Allow the addition of the new name of a ground -->
    <%= g.label :name %>
    <%= g.text_field :name %>
  </div>
  <br>
  <!-- Allow the addition of the description for the new ground -->
  <div class="field">
    <%= g.label :desc %>
    <%= g.text_area :desc %>
  </div>
  <br>
  <!-- Allow the addition of the location of the new ground -->
  <div class="field">
    <%= g.label :location %>
    <%= g.text_field :location %>
  </div>
  <br>
  <!-- button to confirm the above information and make/update an instance of the "Ground" class -->
  <div class="field">
    <%= g.submit %>
  </div>
<% end %>

week6/away_days/app/views/grounds/edit.html.erb
<h1>Edit: <%= @ground.name %></h1>

<!-- locates the file named "_form.html.erb" and embed/run this code in place of the following embedded ruby. In addition, create a variable named ground and give pass it the information -->
<%= render "form", ground: @ground %>

week6/away_days/app/views/grounds/index.html.erb
<h1>Grounds</h1>

<% @grounds.each do |ground| %>
  <h2>Name of ground: <%= link_to "#{ground.name}", ground %></h2>
  <p><%= truncate(ground.desc, :length => 50) %></p>
  <h2>Location: <%= ground.location %></h2>
<% end %>

week6/away_days/app/views/grounds/new.html.erb
<h1>Add a new ground</h1>

<!-- locates the file named "_form.html.erb" and embed/run this code in place of the following embedded ruby. In addition, create a variable named ground and give pass it the information -->
<%= render "form", ground: @ground %>

week6/away_days/app/views/grounds/show.html.erb
<!-- Information on the ground -->
<h1><%= @ground.name %></h1>

<p><%= @ground.desc %></p>

<h2>Location: <%= @ground.location %></h2>

<%= render partial: 'topics/topics', collection: @ground.topics, as: :topic %>

<!-- Edit and delete buttons -->
<%= link_to "Edit Ground Details", edit_ground_path %>
<%= link_to "Delete Ground", @ground, method: :delete %>
<%= link_to "New Topic", new_ground_topic_path(@ground) %>

week6/away_days/app/views/layouts/_nav.html.erb
<!-- link to the home page -->
<%= link_to "Home Page", root_path %>
<!-- link to the list of grounds -->
<%= link_to "Football Grounds", grounds_path %>
<!-- link to new product -->
<%= link_to "Add a new ground", new_ground_path %>

week6/away_days/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwayDays</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- render (display) the code in the "_nav.html.erb" -->
    <%= render "layouts/nav" %>
    <%= yield %>
  </body>
</html>

week6/away_days/app/views/topics/_form.html.erb
<%= form_for [@ground, topic] do |t| %>
  <div class="field">
    <%= t.label :pubs %>
    <%= t.text_area :pubs %>
  </div>
  <div class="field">
    <%= t.label :travel %>
    <%= t.text_area :travel %>
  </div>
  <div class="field">
    <%= t.submit %>
  </div>
<% end %>

week6/away_days/app/views/topics/_topics.html.erb
<h2>Pubs For Away Fans</h2>
<p><%= topic.pubs %></p>
<br>
<h2>Travel Information</h2>
<p><%= topic.location %></p>
<br>
<%= link_to "Edit" edit_ground_topic_path(@ground, topic) %>
<%= link_to "Delete", [@ground, topic], method: :delete %>

week6/away_days/app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

<!-- find the "_form.html.erb" file, run/output that code in place of the embedded ruby below -->
<%= render partial: 'form', locals: {topic: @topic} %>

week6/away_days/app/views/topics/index.html.erb
<h1>Topics#index</h1>
<p>Find me in app/views/topics/index.html.erb</p>

week6/away_days/app/views/topics/new.html.erb
<h1>Add New Topic</h1>

<!-- find the "_form.html.erb" file, run/output that code in place of the embedded ruby below -->
<%= render partial: 'form', locals: {topic: @topic} %>