week6/ourgos/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # go to the static home page
  root 'static#home'

  resources :products
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

week6/ourgos/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

week6/ourgos/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :stock, numericality: {only_integers: true}
end

week6/ourgos/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :products
end

week6/ourgos/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

week6/ourgos/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!

  def index
    # get every product in the table
    @products = Product.all
    # @products = current_user.products
    # this only displays the products which have been made by the current user
  end

  def show
    # show page only displays one product, so target that individucal product
    @product = Product.find params[:id]
  end

  def new
    # create a new instance of the "Product" class
    @product = Product.new
  end

  def edit
    # if the product was not made by the user that is currenty log in, then don't allow them to update the product and instead send them back to the root of products
    if @product.user.id != current_user.id
      redirect_to products_path
    end

    # target the product that we want to edit
    @product = Product.find params[:id]
  end

  def create
    # create a new instance of the class "Product" and sets all the parameters
    @product = Product.new product_params
    respond_to do |format|
      if @product.save
        # if successful then display a message to the user
        format.html{redirect_to @product, notice: "'#{@product.name}' was created"}
      else
        # if there are errors then we want to be taken back to the new page, where the new product is being added
        format.html{render :new}
      end
    end
  end

  def update
    # if the product was not made by the user that is currenty log in, then don't allow them to update the product and instead send them back to the root of products
    if @product.user.id != current_user.id
      redirect_to products_path
    end

    # find the product that we want to update by targeting its unique id
    @product = Product.find params[:id]
    respond_to do |format|
      # if sucessful then display a message to the user
      if @product.update product_params
        format.html{redirect_to @product, notice: "'#{@product.name}' was updated"}
      else
        # if there are errors then we want to be taken back to the edit page
        format.html{render :edit}
      end
    end
  end

  def destroy
    # if the product was not made by the user that is currenty log in, then don't allow them to update the product and instead send them back to the root of products
    if @product.user.id != current_user.id
      redirect_to products_path
    end

    # target the product which we want to delete
    @product = Product.find params[:id]
    # delete the product
    @product.destroy
    # redirect to the root of products
    redirect_to products_path
  end

  def product_params
    # params accesses the parameters sent by the form
    # require('resource name') targets the specific section of params required
    # permit grants write access to these attributes
    product_params = params.require(:product).permit(:name, :desc, :stock, :price)
  end
end

week6/ourgos/app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

week6/ourgos/app/helpers/application_helper.rb
module ApplicationHelper
end

week6/ourgos/app/helpers/products_helper.rb
module ProductsHelper
end

week6/ourgos/app/helpers/static_helper.rb
module StaticHelper
end

week6/ourgos/app/views/layouts/_nav.html.erb
<!-- "products_path" goes to the root of the path -->
<%= link_to "Products Catalogue", products_path %>
<!-- "new_product_path" goes to the actual product itself, not the root of that path -->
<%= link_to "Add a new Product", new_product_path %>

week6/ourgos/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ourgos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/nav" %>
    <%= yield %>
  </body>
</html>

week6/ourgos/app/views/products/_form.html.erb
<%= form_for product do |p| %>
  <!-- if there is errors, when attempting to add a new item, then do the following: -->
  <% if product.errors.any? %>
    <!-- inform the user how many errors there are left to fix -->
    <h2><%= pluralize(product.errors.count, 'error') %> to fix</h2>
    <!-- inform the user the error messages -->
    <% product.errors.full_messages.each do |message| %>
      <ul>
      <li><%= message %></li>
      </ul>
    <% end %>
  <% end %>

  <div class="field">
    <!-- add a label with text "title" -->
    <%= p.label :name %>
    <!-- return the input text as the "varibale" = title -->
    <%= p.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= p.label :desc %>
    <!-- text area so you can put more text in it -->
    <%= p.text_area :desc %>
  </div>
  <br>
  <div class="field">
    <%= p.label :stock %>
    <!-- text area so you can put more text in it -->
    <%= p.text_field :stock %>
  </div>
  <br>
  <div class="field">
    <%= p.label :price %>
    <%= p.text_field :price %>
  </div>
  <br>
  <div class="field">
    <%= p.submit %>
  </div>
<% end %>

week6/ourgos/app/views/products/edit.html.erb
<h1>Edit: <%= @product.name %></h1>

<!-- render the file called "form". Create a new variable named product and pass in the information of @product -->
<%= render "form", product: @product %>

week6/ourgos/app/views/products/index.html.erb
<h1>Products Catalogue</h1>

<% @products.each do |product| %>
  <div class="">
    <%= image_tag "#{product.pic}" %>
    <h2><%= link_to "#{product.name}", product %></h2>
    <!-- truncate the product description to a chosen length. This was automatically ass on the ellipse -->
    <p><%= truncate(product.desc, :length => 50) %></p>
    <p>£<%= product.price %></p>
  </div>
<% end %>

week6/ourgos/app/views/products/new.html.erb
<h1>Add new Product</h1>

<!-- render the file called "form". Create a new variable named product and pass in the information of @product -->
<%= render "form", product: @product %>

week6/ourgos/app/views/products/show.html.erb
<br>
<!-- if the edit/creation of a product has been successful then prompt the user -->
<%= notice %>

<h1><%= @product.name %></h1>

<h2>£<%= @product.price %></h2>

<p>Item Description: <%= @product.desc %></p>

<%= image_tag "#{@product.pic}" %>

<%= link_to "Edit Product Details", edit_product_path %>
<!-- target the @product, and apply the method: delete -->
<%= link_to "Delete Product Details", @product, method: :delete %>