week6/sparta_blogs/config/routes.rb
Rails.application.routes.draw do
  # get 'posts/', to: 'posts#index'
  # get 'posts/new'
  # get 'posts/:id', to: 'posts#edit'
  # get 'posts/:id/edit', to: 'posts#edit'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts do
    resources :comments, :except => [:index, :show, :new]
  end

  root "posts#index"
end

week6/sparta_blogs/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

week6/sparta_blogs/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

week6/sparta_blogs/app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
end

week6/sparta_blogs/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

week6/sparta_blogs/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # before you do anything, do this
  before_action :set_post

  def edit
    @comment = Comment.find params[:id]
  end

  def create
    @comment = @post.comments.create(comment_params)
    @comment.save
    redirect_to @post
  end

  def update
    # find the existing post from our database
    @comment = Comment.find params[:id]
    @comment.update comment_params
    # after the page has been updated, we want to be re-directed to the updated page
    redirect_to @post
  end

  def destroy
    @comment = Comment.find params[:id]
    @comment.destroy
    redirect_to @post
  end

  def set_post
    @post = Post.find params[:post_id]
  end

  def comment_params
    post_params = params.require(:comment).permit(:body, :author)
  end
end

week6/sparta_blogs/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    # on the index page we want to display all the elements in the database
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find params[:id]

  end

  def edit
    @post = Post.find params[:id]
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html{redirect_to @post, notice: "'#{@post.title}' was created"}
      else
        format.html{render :new}
      end
    end
  end

  def update
    # find the existing post from our database
    @post = Post.find params[:id]
    @post.update post_params
    # after the page has been updated, we want to be re-directed to the updated page
    redirect_to @post
  end

  def destroy
    @post = Post.find params[:id]
    @post.destroy
    redirect_to posts_path
  end

  def post_params
    post_params = params.require(:post).permit( :title, :body, :author)
  end
end

week6/sparta_blogs/app/helpers/application_helper.rb
module ApplicationHelper
end

week6/sparta_blogs/app/helpers/post_helper.rb
module PostHelper
end

week6/sparta_blogs/app/views/comments/_comment.html.erb
<p><%= comment.body %></p>
<p>Author: <cite><%= comment.author %></cite></p>
<%= link_to "Edit", edit_post_comment_path(@post, comment) %>
<%= link_to "Delete", [@post,comment], method: :delete %>
<br>

week6/sparta_blogs/app/views/comments/_form.html.erb
<%= form_for [@post,comment] do |c| %>
  <div class="field">
    <!-- add a label with text "title" -->
    <%= c.label :body %>
    <!-- return the input text as the "varibale" = title -->
    <%= c.text_area :body %>
  </div>
  <div class="field">
    <%= c.label :author %>
    <%= c.text_field :author %>
  </div>
  <div class="actions">
    <%= c.submit %>
  </div>
<% end %>

week6/sparta_blogs/app/views/comments/edit.html.erb
<h2>Edit Comment</h2>

<%= render partial: 'form', locals: { comment: @comment } %>

week6/sparta_blogs/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpartaBlogs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

week6/sparta_blogs/app/views/posts/_form.html.erb
<%= form_for post do |p| %>
  <div class="field">
    <!-- add a label with text "title" -->
    <%= p.label :title %>
    <!-- return the input text as the "varibale" = title -->
    <%= p.text_field :title %>
  </div>
  <div class="field">
    <%= p.label :body %>
    <!-- text area so you can put more text in it -->
    <%= p.text_area :body %>
  </div>
  <div class="field">
    <%= p.label :author %>
    <%= p.text_field :author %>
  </div>
  <br>
  <div class="field">
    <%= p.submit %>
  </div>
<% end %>

week6/sparta_blogs/app/views/posts/edit.html.erb
<%= link_to 'Home', posts_path %>
<h1>Edit Post</h1>

<%= render 'form', post: @post %>

week6/sparta_blogs/app/views/posts/index.html.erb
<%= link_to "New Post", new_post_path %>

<h1>SpartaBlogs</h1>
<% @posts.each do |post| %>
  <!-- name of link, then where we want the link to go -->
  <%= link_to "#{post.title}", post %>
  <p><%= post.body %></p>
  <p><%= post.author %></p>
  <br>
  <!-- go to edit page for this current post. The varibale is to tell the computer which post we wish to edit -->
  <%= link_to "Edit", edit_post_path(post) %>

  <%= link_to "Delete", post, method: :delete %>
  <br>
  <br>
  <br>
<% end %>

week6/sparta_blogs/app/views/posts/new.html.erb
<%= link_to 'Home', posts_path %>
<h1>Create a new Post</h1>

<%= render 'form', post: @post %>

week6/sparta_blogs/app/views/posts/show.html.erb
<%= link_to "Home", posts_path %>
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>
<p><%= @post.author %></p>
<%= link_to "Edit", edit_post_path(@post) %>
<%= link_to "Delete", @post, method: :delete %>

<hr>

<h2>Comments section</h2>

<!-- pass in a collection of information, and passes it in as "comment". Treats each bit of information individually -->
<%= render partial: 'comments/comment', collection: @post.comments, as: :comment%>

<hr>

<h2>Add Comment</h2>

<%= render partial: 'comments/form', locals: { comment: @post.comments.new }%>